config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :families
  resources :children
  resources :checks
  resources :programs
  resources :memberships  
  
  get "/sign_in", to: "sessions#new", as: :sign_in
  post "/sign_in", to: "sessions#create", as: :create_sign_in
  get "/sign_out", to: "sessions#destroy", as: :sign_out

  root 'sessions#new'
end

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id                :integer          not null, primary key
#  parent_first_name :string
#  parent_last_name  :string
#  spouse_name       :string
#  phone             :string
#  address           :string
#  password          :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Family < ActiveRecord::Base
  has_many :children
  has_many :checks
  
  validates :password, uniqueness: true
  validates :parent_first_name, :parent_last_name, :password, :phone, :address, presence: true
    
  def self.authenticate(parent_last_name, password)
    family = find_by_parent_last_name(parent_last_name)
    
    if family && family.password == password
      family
    else
      nil
    end
  end
  
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  
  def new
    @family = Family.new
  end
  
  def create
    @family = Family.new(family_params)
    @family.password = SecureRandom.hex(2)
    
    if @family.save
      redirect_to root_url, notice: "Successfully created!"
    else
      render :new, alert: "Something was wrong. Try again."
    end
  end
  
  def index
    @families = Family.all
  end
  
  def show
    @family = Family.find(params[:id])
  end
  
  def family_params
    params.require(:family).permit(:parent_first_name, :parent_last_name, :phone, :spouse_name, :address, :password)
  end
end

app/views/families/index.html.erb
<h1>Families</h1>

<% @families.each do |family| %>
  <table class="family_table">
    <tr>
      <td>
        <%= link_to family.parent_first_name, family %>
        <%= link_to family.parent_last_name, family %> &
        <%= link_to family.spouse_name, family %> :
      </td>
      <td><%= family.phone %></td>
      <td><%= family.address %></td>
    </tr>
  </table>
<% end %>

<%= link_to "Add a family", new_family_path %>

app/views/families/new.html.erb
<div class="new_family_form">
  <%= form_for @family do |f| %>
    <%= f.label :parent_first_name %>
    <%= f.text_field :parent_first_name %>
    <br>
    <%= f.label :parent_last_name %>
    <%= f.text_field :parent_last_name %>
    <br>
    <%= f.label :spouse_name %>
    <%= f.text_field :spouse_name %>
    <br>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
    <br>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/families/show.html.erb
<h2>Family</h2>
<div class="family_show">
	<%= @family.parent_first_name %> & 
	<%= @family.spouse_name %>
	<%= @family.parent_last_name %>
	<br>
	<%= @family.phone %>
	<%= @family.address %>
</div>

<h2>Children</h2>
<div>
<% @family.children.each do |child| %>
  <%= child.child_first_name %>
  <%= child.child_last_name %>
  <br>
<% end %>
</div>

<div><%= link_to "Add a child to this family", new_child_path %></div>